name: Lint
on:
  pull_request:
    branches:
      - main
    paths:
      - "platform/**/*.mdx"
      - "platform/**/*.md"
      - "vcluster/**/*.mdx"
      - "vcluster/**/*.md"
      - "vcluster_versioned_docs/**/*.mdx"
      - "vcluster_versioned_docs/**/*.md"
      - .github/workflows/reviewdog.yaml
      - "*.md"
permissions:
  pull-requests: write
jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Get all changed files and use a comma separator in the output
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          separator: ","
          files: |
            platform/**/*.mdx
            platform/**/*.md
            vcluster/**/*.mdx
            vcluster/**/*.md
            vcluster_versioned_docs/**/*.mdx
            vcluster_versioned_docs/**/*.md
      - name: Run Vale with Reviewdog
        uses: errata-ai/vale-action@reviewdog
        if: steps.changed-files.outputs.all_changed_files != ''
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          reporter: github-pr-check
          version: 3.7.1
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
          filter_mode: file
      - name: Debug - Print changed files
        run: |
          echo "Changed files (comma-separated):"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
