name: Lint
on:
  pull_request:
    branches:
      - main
    paths:
      - "platform/**/*.mdx"
      - "platform/**/*.md"
      - "vcluster/**/*.mdx"
      - "vcluster/**/*.md"
      - "vcluster_versioned_docs/**/*.mdx"
      - "vcluster_versioned_docs/**/*.md"
      - .github/workflows/reviewdog.yaml
      - "*.md"
permissions:
  pull-requests: write
jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files-json
        uses: tj-actions/changed-files@v45
        with:
          files: |
            platform/**/*.mdx
            platform/**/*.md
            vcluster/**/*.mdx
            vcluster/**/*.md
            vcluster_versioned_docs/**/*.mdx
            vcluster_versioned_docs/**/*.md
          json: 'true'
      - name: Prepare files for Vale
        id: prepare-files
        run: |
          CHANGED_FILES=$(echo '${{ steps.changed-files-json.outputs.all_changed_files }}' | jq -r 'join(" ")')
          echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT
      - name: Run Vale with Reviewdog
        uses: errata-ai/vale-action@reviewdog
        if: steps.prepare-files.outputs.files != ''
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          reporter: github-pr-review
          version: 3.7.1
          files: ${{ steps.prepare-files.outputs.files }}
      - name: Debug - Print changed files
        run: |
          echo "Changed files JSON:"
          echo '${{ steps.changed-files-json.outputs.all_changed_files }}'
          echo "Prepared files for Vale:"
          echo "${{ steps.prepare-files.outputs.files }}"
